config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  mount ActionCable.server ,at: '/cable'
  resources :articles
  resources :users
  resources :messages
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'new', to: 'sessions#new'
  post 'create', to: 'sessions#create'
  delete 'destroy', to: 'sessions#destroy'
  get 'index', to: 'chatrooms#index'
  post 'message', to: 'messages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :article_categories
  has_many :categories , through: :article_categories
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5, maximum: 25}
  validates :description, presence: true, length: {minimum: 5}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :article
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true
  scope :custome_display, -> { order(:created_at).last(20)}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :messages
  has_secure_password
  before_save {self.email = self.email.downcase}
  validates :username, presence: true, uniqueness: true, length: {minimum: 5, maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
  uniqueness: { case_sensitive: false },
  format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:danger] = 'You should log in first'
      #redirect_to root_path
      redirect_to new_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_params)
    if @article.save
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(articles_params)
      redirect_to articles_path
      flash[:message] = "Article successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to articles_path
      flash[:message] = "Article successfully Destroyed"
    end
  end
  private
    def articles_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custome_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                                    message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_to_logged_in, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'successfully logged in'
      redirect_to :controller => 'chatrooms', :action => 'index'

      #redirect_to users_path
    else
      flash.now[:error] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'successfully logged out'
    redirect_to new_path
  end

  def redirect_to_logged_in
    if logged_in?
      flash[:error] = 'You are already logged in'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:message] = "Welcome to our app #{user_params[:username]}"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  def show
    @user = User.find(params[:id])

  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravator_id = Digest::MD5::hexdigest(user.email.downcase)
    gravator_url = "https://secure.gravator.com/#{gravator_id}"
    image_tag(gravator_url, alt: user.username, class: 'img-circle')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<div class="article_form">
  <%= form_for @article do |form| %>

   <%= form.label :title %>

  <p class="input_area">
   <%= form.text_field :title, placeholder: 'title' %>
  </p>

   <%= form.label :description %>

  <p class="input_area">
   <%= form.text_area :description, placeholder: 'description' %>
  </p>
  <%= form.submit %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<%= link_to 'show user', user_path(User.first) %>
<%= flash[:message] %><br><br>
<%= link_to 'Add new Article', new_article_path %>
<div>
  <table>
    <tr><th>Title</th><th>Description</th></tr>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td class="content"><%= article.description %></td>
      <td><%= link_to 'edit', edit_article_path(article) %>
      <td><%= link_to 'delete', article_path(article), method: :delete , data: "Are you sure" %>
    </tr>
    <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div>
  <table>
    <tr><th>Title</th><th>Description</th></tr>
    <tr>
      <td><%= @article.title %></td>
      <td><%= @article.description %></td>
    </tr>
  </table>
</div>

<%= link_to 'back', articles_path %>

app/views/chatrooms/chat_index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say Something
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chatrooms/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say Something
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chatrooms/login_form.html.erb
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
        <div class="field">
          <label>Username</label>
          <div class="ui left icon input">
            <input type="text" placeholder="Username">
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui left icon input">
            <input type="password">
            <i class="lock icon"></i>
          </div>
        </div>
        <div class="ui blue submit button">Login</div>
      </div>
    </div>
    <div class="middle aligned column">
      <div class="ui big button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>

app/views/layouts/_message.html.erb
<% flash.each do |message_type, message_content| %>
<div class="ui message <%= message_type %> message transition">
  <i class="close icon"></i>
  <div class="header">
    <%= message_content %>
  </div>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui tiny inverted menu">
  <div class="ui floating labeled icon dropdown button">
  <i class="filter icon"></i>
  <span class="text">Select App</span>
  <div class="menu">
    <div class="divider"></div>
    <div class="item">
      <i class="attention icon">
      <%= link_to 'Article', articles_path %></i>
    </div>
    <div class="item">
      <i class="comment icon"></i>
      Announcement
    </div>
    <div class="item">
      <i class="meetup icon">
      <%= link_to 'Chat App', new_path %></i>
    </div>
  </div>
</div>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu container">
        <% if logged_in? %>
          <a class="item" ><%= link_to 'Log out', destroy_path, method: :delete %></a>
        <% else %>
          <a class="item" ><%= link_to 'Log In' , new_path %></a>
        <% end %>
      </div>
    </div>
    <% if !logged_in? %>
    <div class="item">
      <%= link_to 'Log In' , new_path, class: "ui primary button" %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Udamy Learnings</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class= "ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
hellow

app/views/users/index.html.erb
welcome

app/views/users/new.html.erb
<div class="user_form">
  <%= form_for @user do |form| %>

   <%= form.label :username %>

  <p class="input_area">
   <%= form.text_field :username, placeholder: 'Your name' %>
  </p>

   <%= form.label :email %>

  <p class="input_area">
   <%= form.text_field :email, placeholder: 'Your email', class: 'form_control' %>
  </p>
  <%= form.label :password %>
  <p class="input_area">
    <%= form.password_field :password, placeholder: 'create a strong password'%>
  </p>
  <%= form.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<h3> Welcome to <%= @user.username %></h3>
<div>
  <div class = "col-md-4 col-md-offset-4 center" >
    <%= gravatar_for @user %>
  </div>
</div>